### ISSUE TITLE
error regarding vis.py

### ISSUE THREAD

**Issue by sumis2140** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#13]
Hai @seominseok0429 

I tried to run code its works fine  but  i have an error on `vis.py` 

```
Traceback (most recent call last):
  File "vis.py", line 10, in <module>
    from models.model import generate_model
ModuleNotFoundError: No module named 'models'
```

Thanks

**Comment by seominseok0429** [comment]
Ours full code available at [CODE](https://drive.google.com/file/d/1DMJR4cR97FzDXfmfPgg6LKeE7LT7x79d/view?usp=sharing)

Thanks

**Comment by Dev-ori** [comment]
Thank you for Full code. 
By your new CODE, We could see the "models" folder in the "VIS" folder 
But It seems still there is no 'model' file. and  it occurs error at vis.py file. 

So, Could you please upload it?

**Comment by seominseok0429** [comment]
Oops. I'll upload it!

**Comment by seominseok0429** [comment]
This is the modified download link. https://drive.google.com/file/d/1xYsBiCSmXjE0BwoiH_Bcm4AWaA1pESHF/view?usp=sharing
