### ISSUE TITLE
Evaluation Strategy Is Incorrect

### ISSUE THREAD

**Issue by pmcb99** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#14]
You cannot calculate the AUC score in this way, as it leads to a higher overall AUC in the end.

Since you increment the AUC for every new addition of a video pair, the early increments are closer to 1 than 0, which inflates the final AUC. If anyone wishes to test this, use a small subset of the dataset and you will see very high AUC scores.

**Comment by seominseok0429** [comment]
Compare with the code in the link: https://github.com/junha-kim/Learning-to-Adapt-to-Unseen-Abnormal-Activities/blob/master/evaluation.py#L27-L128

**Comment by pmcb99** [comment]
I have already compared the code and it is wrong. You need to verify the code independently.

**Comment by seominseok0429** [comment]
At the time of writing the code, it was confirmed that the performance was similar to the evaluation code of the link.

 It's been a long time and it's difficult to accurately analyze the code. 
 
 Can you edit the code and commit it? Then I will merge.
