### ISSUE TITLE
Need help regarding testing the model with my own Videos!

### ISSUE THREAD

**Issue by Zain-Gill123** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#3]
Could you please guide me in understanding how to TEST my own videos using this model. I'm new. I am unable to interpret how the data is labelled in the Test_Anomalyv2.txt file. I want to add my own videos in it to test but I have no idea how to. Any kind of help would be highly appreciated!

[test_anomalyv2.txt](https://github.com/seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch/files/6828551/test_anomalyv2.txt)

**Comment by seominseok0429** [comment]
We are going to distribute the test code. Sorry for the late reply.

**Comment by Chuttyboy** [comment]
> We are going to distribute the test code. Sorry for the late reply.

Could you please notify us once test code distributed is done , Beacause its very usefull for testing our own data's

**Comment by Chuttyboy** [comment]
> We are going to distribute the test code. Sorry for the late reply.

@seominseok0429 

After training and testing how to predict anomalies in videos could you please tell us, that's the only difficulty I face

Thank you

**Comment by seominseok0429** [comment]
@Chuttyboy We will share the code after cleaning it up.

**Comment by Chuttyboy** [comment]
> @Chuttyboy We will share the code after cleaning it up.

@seominseok0429 

when test code will upload?

Thank you

**Comment by bdubbs09** [comment]
@seominseok0429 @Chuttyboy @Zain-Gill123 Has this been closed or resolved? I am trying to do the same thing at the moment.

**Comment by Zain-Gill123** [comment]
> @seominseok0429 @Chuttyboy @Zain-Gill123 Has this been closed or resolved? I am trying to do the same thing at the moment.

Nah. Nothing. It was not resolved.

**Comment by Chuttyboy** [comment]
> @Chuttyboy We will share the code after cleaning it up.

@seominseok0429 @Zain-Gill123 

Is there any update regarding the test code ?? after completion of training on how to test the model with videos ???

Thanks

**Comment by seominseok0429** [comment]
Ours full code available at [CODE](https://drive.google.com/file/d/1DMJR4cR97FzDXfmfPgg6LKeE7LT7x79d/view?usp=sharing)
