### ISSUE TITLE
Run code with cpu ??

### ISSUE THREAD

**Issue by Chuttyboy** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#4]
Hai @seominseok0429 

CPU 로 이 코드를 실행하는 방법

감사 해요

**Comment by seominseok0429** [comment]
It will be uploaded within this week.

**Comment by Chuttyboy** [comment]
> It will be uploaded within this week.

Thank you so much it will be very useful for my studies

**Comment by seominseok0429** [comment]
I uploaded the code.

**Comment by Chuttyboy** [comment]
> I uploaded the code.

Heartly Thank you @seominseok0429

**Comment by Chuttyboy** [comment]
Hai @seominseok0429  

![er](https://user-images.githubusercontent.com/79959547/127626894-cadcf3a6-ff5b-45c1-9502-3796fb551a8f.png)

I got this error while running main.py, suggested a solution to downgrade numpy even after too error was repeated.
