### ISSUE TITLE
How to extract the features of my video in I3D?

### ISSUE THREAD

**Issue by zzxzzt333** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#6]
Thank you very much for your work. In order to get the same effect as you.I want to know how to process and train the original video data to get the segment features you share. Can you share the code?

**Comment by seominseok0429** [comment]
We will share the code after cleaning it up.

**Comment by jinayvora** [comment]
Can you please share the code if its cleaned up...and just give us the basic idea about how to execute it as we are new in this....Thank You!

**Comment by seominseok0429** [comment]
Ours full code available at [CODE](https://drive.google.com/file/d/1DMJR4cR97FzDXfmfPgg6LKeE7LT7x79d/view?usp=sharing)
