### ISSUE TITLE
Different evaluation strategy

### ISSUE THREAD

**Issue by LiUzHiAn** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#8]
Is your evaluation strategy the same as the official? 

I notice you average the AUCs of 140 testing abnormal videos. If I didn't remember wrong, the official calculated the whole videos at the same time.

**Comment by LiUzHiAn** [comment]
Have you ever tried to evaluate the AUC of all the videos at once?  

To be more specific, suppose we have 3 test videos with 1000 frames each. And the first videos are normal, the rest two are abnormal ones. You should contact the gt_labels and predicted scores of all three videos and use sklearn to calculate the AUC.
What is the result then?

Thx.

**Comment by Karthikeya-t** [comment]
Can you please tell me How to add evaluate this model , Auc curve code of this model 

Thanks for helping

**Comment by wjtan99** [comment]
@LiUzHiAn I tried your way, and the AUC is not identical but about the same.  
@seominseok0429 What training parameters did you use? I got AUC=0.82, but 0.845. Thanks.

**Comment by seominseok0429** [comment]
Ours full code available at [CODE](https://drive.google.com/file/d/1DMJR4cR97FzDXfmfPgg6LKeE7LT7x79d/view?usp=sharing)
