### ISSUE TITLE
feature extraction method

### ISSUE THREAD

**Issue by Henryy-rs** [seominseok0429/Real-world-Anomaly-Detection-in-Surveillance-Videos-pytorch#9]
안녕하세요! 컴퓨터비전 공부 중인 학생입니다.

혹시 특징 추출을 어떻게 하셨는지 알 수 있을까요?

사용하신 pretraind model이 궁금합니다!

**Comment by seominseok0429** [comment]
mmaction에서 제공하는 i3d 모델로 모든 feture를 저장하고 , original paper의 구현대로 구간을 설정하여 추출 하였습니당

**Comment by Henryy-rs** [comment]
감사합니다ㅎㅎ

**Comment by Henryy-rs** [comment]
혹시 특징추출하는데 얼마나 걸리셨나요?!

**Comment by 137xiaoyu** [comment]
> mmaction에서 제공하는 i3d 모델로 모든 feture를 저장하고 , original paper의 구현대로 구간을 설정하여 추출 하였습니당

The dataset link you provided is the same as [this repo](https://github.com/junha-kim/Learning-to-Adapt-to-Unseen-Abnormal-Activities), did your method get the same features as theirs? Have you verified it?

**Comment by seominseok0429** [comment]
Ours full code available at [CODE](https://drive.google.com/file/d/1DMJR4cR97FzDXfmfPgg6LKeE7LT7x79d/view?usp=sharing)
